"""add texture_asset_id to wardrobe_items

Revision ID: 46723ad3f2cb
Revises: 7758f9cf0693
Create Date: 2026-08-02 22:58:31.828603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46723ad3f2cb'
down_revision: Union[str, Sequence[str], None] = '7758f9cf0693'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wardrobe_items', sa.Column('texture_asset_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'wardrobe_items', 'assets', ['texture_asset_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wardrobe_items', type_='foreignkey')
    op.drop_column('wardrobe_items', 'texture_asset_id')
    # ### end Alembic commands ###
