"""add ai_photo_asset_id to wardrobe_items

Revision ID: e0c8c2dfe8ca
Revises: e4c749518692
Create Date: 2026-08-03 19:53:07.296176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0c8c2dfe8ca'
down_revision: Union[str, Sequence[str], None] = 'e4c749518692'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wardrobe_items', sa.Column('ai_photo_asset_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'wardrobe_items', 'assets', ['ai_photo_asset_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wardrobe_items', type_='foreignkey')
    op.drop_column('wardrobe_items', 'ai_photo_asset_id')
    # ### end Alembic commands ###
