"""add garment_ml_analyses table

Revision ID: e4c749518692
Revises: 46723ad3f2cb
Create Date: 2026-08-03 07:00:12.800397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e4c749518692'
down_revision: Union[str, Sequence[str], None] = '46723ad3f2cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('garment_ml_analyses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('wardrobe_item_id', sa.Uuid(), nullable=False),
    sa.Column('raw_labels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_likely_garment', sa.Boolean(), nullable=True),
    sa.Column('top_label', sa.String(length=255), nullable=True),
    sa.Column('top_confidence', sa.Float(), nullable=True),
    sa.Column('segmentation_succeeded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['wardrobe_item_id'], ['wardrobe_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_garment_ml_analyses_wardrobe_item_id'), 'garment_ml_analyses', ['wardrobe_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_garment_ml_analyses_wardrobe_item_id'), table_name='garment_ml_analyses')
    op.drop_table('garment_ml_analyses')
    # ### end Alembic commands ###
